-- 创建城市信息表
CREATE TABLE `city_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `city_name` varchar(100) DEFAULT NULL COMMENT '城市中文名',
  `city_english_name` varchar(200) DEFAULT NULL COMMENT '城市英文名',
  `province_name` varchar(100) DEFAULT NULL COMMENT '省份中文名',
  `province_english_name` varchar(200) DEFAULT NULL COMMENT '省份英文名',
  `country_name` varchar(100) DEFAULT NULL COMMENT '国家中文名',
  `country_english_name` varchar(200) DEFAULT NULL COMMENT '国家英文名',
  `city_code` varchar(20) DEFAULT NULL COMMENT '城市编码',
  `sort` int DEFAULT '0' COMMENT '排序',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态（1-启用，0-禁用）',
  `remarks` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  PRIMARY KEY (`id`),
  KEY `idx_city_name` (`city_name`),
  KEY `idx_province_name` (`province_name`),
  KEY `idx_country_name` (`country_name`),
  KEY `idx_city_code` (`city_code`),
  KEY `idx_status` (`status`),
  KEY `idx_org_id` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='城市信息表';

-- 插入中国主要城市数据
INSERT INTO `city_info` (`city_name`, `city_english_name`, `province_name`, `province_english_name`, `country_name`, `country_english_name`, `city_code`, `sort`, `status`, `remarks`, `create_by`, `update_by`, `org_id`) VALUES
('北京市', 'Beijing', '北京市', 'Beijing', '中国', 'China', '110000', 1, 1, '直辖市', 'admin', 'admin', 1),
('上海市', 'Shanghai', '上海市', 'Shanghai', '中国', 'China', '310000', 2, 1, '直辖市', 'admin', 'admin', 1),
('广州市', 'Guangzhou', '广东省', 'Guangdong', '中国', 'China', '440100', 3, 1, '省会城市', 'admin', 'admin', 1),
('深圳市', 'Shenzhen', '广东省', 'Guangdong', '中国', 'China', '440300', 4, 1, '计划单列市', 'admin', 'admin', 1),
('天津市', 'Tianjin', '天津市', 'Tianjin', '中国', 'China', '120000', 5, 1, '直辖市', 'admin', 'admin', 1),
('重庆市', 'Chongqing', '重庆市', 'Chongqing', '中国', 'China', '500000', 6, 1, '直辖市', 'admin', 'admin', 1),
('杭州市', 'Hangzhou', '浙江省', 'Zhejiang', '中国', 'China', '330100', 7, 1, '省会城市', 'admin', 'admin', 1),
('南京市', 'Nanjing', '江苏省', 'Jiangsu', '中国', 'China', '320100', 8, 1, '省会城市', 'admin', 'admin', 1),
('武汉市', 'Wuhan', '湖北省', 'Hubei', '中国', 'China', '420100', 9, 1, '省会城市', 'admin', 'admin', 1),
('成都市', 'Chengdu', '四川省', 'Sichuan', '中国', 'China', '510100', 10, 1, '省会城市', 'admin', 'admin', 1),
('西安市', 'Xi\'an', '陕西省', 'Shaanxi', '中国', 'China', '610100', 11, 1, '省会城市', 'admin', 'admin', 1),
('青岛市', 'Qingdao', '山东省', 'Shandong', '中国', 'China', '370200', 12, 1, '计划单列市', 'admin', 'admin', 1),
('大连市', 'Dalian', '辽宁省', 'Liaoning', '中国', 'China', '210200', 13, 1, '计划单列市', 'admin', 'admin', 1),
('宁波市', 'Ningbo', '浙江省', 'Zhejiang', '中国', 'China', '330200', 14, 1, '计划单列市', 'admin', 'admin', 1),
('厦门市', 'Xiamen', '福建省', 'Fujian', '中国', 'China', '350200', 15, 1, '计划单列市', 'admin', 'admin', 1),
('苏州市', 'Suzhou', '江苏省', 'Jiangsu', '中国', 'China', '320500', 16, 1, '地级市', 'admin', 'admin', 1),
('无锡市', 'Wuxi', '江苏省', 'Jiangsu', '中国', 'China', '320200', 17, 1, '地级市', 'admin', 'admin', 1),
('长沙市', 'Changsha', '湖南省', 'Hunan', '中国', 'China', '430100', 18, 1, '省会城市', 'admin', 'admin', 1),
('郑州市', 'Zhengzhou', '河南省', 'Henan', '中国', 'China', '410100', 19, 1, '省会城市', 'admin', 'admin', 1),
('沈阳市', 'Shenyang', '辽宁省', 'Liaoning', '中国', 'China', '210100', 20, 1, '省会城市', 'admin', 'admin', 1);